#!/bin/bash

argument() { # argument verb pacman-string arg-help info
	printf '\t%-13s | %-35s --- %s\n' "$1" "$2  $3" "$4"
}

printf 'pachelp: Prints how to use pacman to do VERB\n\n'
argument 'install' 'pacman -S' 'PackageName' 'Installs the package from the remote repository'
argument 'update' 'pacman -Syu' 'PackageName' 'Installs PackageName (if given) and updates all packages on the system'
argument 'search' 'pacman -Ss' 'Search Keywords' 'Searches for a package whose name or description contains each Keyword'
argument 'remove' 'pacman -Rns' 'PackageName' 'Removes PackageName and all its now-unneeded dependencies'
argument 'get-owner' 'pacman -Qo' 'File' 'Prints the package that created or owns File'
argument 'list-files' 'pacman -Ql' 'PackageName' 'Prints all the files owned by PackageName'
